PREFIX bods: <http://bods.openownership.org/vocabulary/>
PREFIX bodsrisk: <http://bods.openownership.org/risk/>

SELECT ?riskEntity ?relationship (GROUP_CONCAT(DISTINCT ?risk;separator=",") as ?risks)
WHERE {
    ?riskEntity bods:ownsOrControls+ ?target .
    ?riskEntity bodsrisk:hasRisk ?risk .
}
GROUP BY ?riskEntity ?relationship
