services:
  elasticsearch:
    container_name: bods-risk-elasticsearch
    image: "docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION}"
    ports:
      - 9200:9200
    environment:
      - "ES_JAVA_OPTS=-Xms8g -Xmx8g"
  graphdb:
    container_name: bods-risk-graphdb
    image: "ontotext/graphdb:${GRAPHDB_VERSION}"
    ports:
      - 7200:7200
    environment:
      - "GDB_HEAP_SIZE=4g"
