app:
  elasticsearch:
    host: localhost
    port: 9200
    username: elastic
    password: QBrEoenGBdcaY1LROzIR
  rdf:
    connection-url: http://localhost:7200
    username: admin
    password: admin
  data-import:
    importer-names: IcijDataset

micronaut:
  views:
    pebble:
      cache-active: false
