PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX bods:  <http://bods.openownership.org/vocabulary/>
PREFIX bodsr: <http://bods.openownership.org/resource/>
PREFIX onto:  <http://www.ontotext.com/>

SELECT ?parent ?child ?controlStatement
WHERE {
    bodsr:openownership-register-6893468895050709685 bods:ownsOrControls* ?parent .
    ?controlStatement bods:hasInterestedParty ?parent .
    ?controlStatement bods:hasSubject ?child .
    FILTER(STRSTARTS(STR(?parent), STR(bodsr:)))
    FILTER(STRSTARTS(STR(?child), STR(bodsr:)))
}
GROUP BY ?parent ?child ?controlStatement
