PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX bods:  <http://bods.openownership.org/vocabulary/>
PREFIX bodsr: <http://bods.openownership.org/resource/>
PREFIX onto:  <http://www.ontotext.com/>

SELECT ?ubo ?parent ?child ?controlStatement
FROM onto:disable-sameAs
WHERE {
    ?ubo bods:ownsOrControls* ?parent .
    ?ubo rdf:type bods:Person .
    ?controlStatement bods:hasInterestedParty ?parent .
    ?controlStatement bods:hasSubject ?child .
    ?child bods:ownsOrControls* ?target .
}
GROUP BY ?ubo ?parent ?child ?controlStatement
