PREFIX rdf:      <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX foaf:     <http://xmlns.com/foaf/0.1/>
PREFIX bods:     <http://bods.openownership.org/vocabulary/>
PREFIX bodsr: <http://bods.openownership.org/resource/>

SELECT ?ultimateParent
WHERE  {
    ?ultimateParent bods:ownsOrControls* ?target .
    ?ultimateParent rdf:type bods:Entity .
    FILTER(STRSTARTS(STR(?ultimateParent), STR(bodsr:)))

    FILTER NOT EXISTS {
        ?s bods:ownsOrControls ?ultimateParent .
        ?s rdf:type bods:Entity .
    }
}

